### All-In-One Plugin Configuration ###

# Spawn location #

spawn:
  world: ''
  x: 0
  y: 0
  z: 0
  yaw: 0
  pitch: 0

# MySQL Connection #

mysql:
  server: ''
  username: ''
  password: ''

# AntiSwear #

antiswear: