main: AIO.aio
version: 1.0
developers: [DaniFoldi, ApocalypseDJ]
name: All-In-One_Plugin
softdepend: [Vault]
commands:
    kickall:
    kick:
    nick:
    ping:
    privatemsg:
    worlds:
    sun:
    rain:
    storm:
    
    