main: AIO.aio
version: 1.0
developers: [DaniFoldi, ApocalypseDJ]
name: All-In-One_Plugin
depend: [Vault, SuperVanish, WorldEdit, WorldGuard, Votifier]
commands:
    kickall:
    kick:
    nick:
    ping:
    msg:
      aliases: [m, t, w, whisper, tell]
    worlds:
    sun:
    rain:
    storm:
    survival:
        aliases: [s, gms, gm0]
    creative:
        aliases: [c, gmc, gm1]
    adventure:
        aliases: [a, gma, gm2]
    spectator:
        aliases: [gmsp, gm3]
    reply:
        aliases: [r]
    advertisement:
        aliases: [advertise, ad]
    dawn:
        aliases: [sunrise]
    morning:
    day:
    noon:
    afternoon:
    night:
    dusk:
        aliases: [sunset]
    midnight:
    balance:
        aliases: [b, bal, money, mon]
    pay:
        aliases: [transfer]
    economy:
        aliases: [eco]
    heal:
    feed:
    fly:
    god:
    kittycannon:
        aliases: [kc, f]
    tntcannon:
        aliases: [tnt]
    giveself:
        aliases: [i, item]
    tpa:
    tpahere:
    tpaccept:
        aliases: [tpyes]
    tpdeny:
        aliases: [tpno]
    tptoggle:
    tp:
    tphere:
    tpall:
    spawn:
    setspawn:
    test:
    more:
    repair:
    skull:
    craftbench:
        aliases: [wb, cb, workbench, craftingtable, ct]
    enchanttable:
        aliases: [etable, et]
    enderchest:
        aliases: [ec, echest]
    flyspeed:
        aliases: [fspeed]
    nearby:
        aliases: [near]
    motd:
    rules:
    news:
    freeze:
    unsafeenchant:
        aliases: [uenchant, ue]
    banner:
    warp:
        description: Warping...
    setwarp:
        description: Creates a new warp.
    delwarp:
        description: Deletes an existing warp.
    warplist:
        aliases: [warps]
        description: Displays the warplist.
    warpreload:
        description: Reloads the configuration.
    lightning:
        aliases: [thor]
    spawner:
    whois:
    spawnmob:
    vanish:
        aliases: [v]
    adminonly:
        aliases: [ao, ac, adminchat]
    rename:
    lottery:
        aliases: [lot]
    hologram:
    dropparty:
        aliases: [dp]
    invsee:
    endersee:
    nightvision:
        aliases: [nv]
    crates:
        aliases: [crate]
    antiswear:
        aliases: [as]
    cell:
    auction:
        aliases: [auc]
    bid:
    key:
    balancetop:
        aliases: [baltop]
    axe:
    clearlag:
        aliases: [clag, lag, antilag]
    visit:
        aliases: [pwarp]
    banknote:
    withdrawxp:
    sudo:
    coin:
