main: AIO.aio
version: 1.0
developers: [DaniFoldi, ApocalypseDJ]
name: All-In-One_Plugin
softdepend: [Vault]
commands:
    kickall:
    kick:
    nick:
    ping:
    privatemsg:
    worlds:
    sun:
    rain:
    storm:
    gm:
    survival:
    	aliases: [s, gms, gm0]
    creative:
    	aliases: [c, gmc, gm1]
    adventure:
    	aliases: [a, gma, gm2]
    spectator:
    	aliases: [sp, gmsp, gm3]
    